# Site Settings
title: Lumina
url: https://protekti.github.io/Lumina

# Build Settings
markdown: kramdown
theme: jekyll-theme-cayman # or any other Jekyll theme you prefer

# Navigation
nav_links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog

# Plugins
plugins:
  - jekyll-feed # for generating an RSS feed
  - jekyll-seo-tag # for better SEO

# Author
author:
  name: protekti
  email: protekti08@gmail.com

# Social Links
social:
  - title: GitHub
    url: https://github.com/protekti
    
seo:
  type: website
  title: Your Awesome Website
  description: A brief description of your website
  image: /assets/images/your-image.png # path to your website's image for sharing
  keywords: [your, keywords, here]

# Build and Development
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
